# Generated by Django 6.0.1 on 2026-01-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
